name: dv2_public_data_demo
version: "1.0.0"
config-version: 2

profile: dv2_public_data_demo

model-paths: [models]
seed-paths: [seeds]
test-paths: [tests]
analysis-paths: [analyses]
macro-paths: [macros]
snapshot-paths: [snapshots]

target-path: target
clean-targets: [target, dbt_packages, logs]

vars:
  hash: 'MD5'
  load_datetime_col_type: 'TIMESTAMP'

models:
  dv2_public_data_demo:
    staging:
      +materialized: view
      +schema: staging
      v_stg_trips_with_zones:
        +materialized: table
    raw_vault:
      +materialized: incremental
      +schema: raw_vault
      +on_schema_change: fail
    business_vault:
      +materialized: table
      +schema: business_vault
    information_mart:
      +materialized: table
      +schema: information_mart

flags:
  require_generic_test_arguments_property: true
  source_freshness_run_project_hooks: true
